/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2020-07-17 11:46:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user.freeboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class freeboardView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>자유게시글 정보</title>\r\n");
      out.write("<!-- 이미지 슬라이드 사이즈 조정 -->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".carousel{\r\n");
      out.write("\twidth:200px;\r\n");
      out.write("    height:150px;\r\n");
      out.write("    margin-left: 200px;\r\n");
      out.write("}\r\n");
      out.write(".carousel-inner > .item > img{\r\n");
      out.write("    width:200px;\r\n");
      out.write("    height:150px;\r\n");
      out.write("}       \r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t// 섬머노트를 div를 활용한 textarea에 추가.\r\n");
      out.write("\t// http://summernote.org 활용\r\n");
      out.write("    $('#bo_content').summernote({\r\n");
      out.write("\t\t\theight: 150,\r\n");
      out.write("\t\t\tcodemirror: {\r\n");
      out.write("\t\t\ttheme: 'monokai'\r\n");
      out.write("\t\t}\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    // 초기값 설정\r\n");
      out.write("    $('input[name=bo_title]').val('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeboardInfo.bo_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("');\r\n");
      out.write("    $('input[name=bo_nickname]').val('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeboardInfo.bo_nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("');\r\n");
      out.write("    $('input[name=bo_pwd]').val('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeboardInfo.bo_pwd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("');\r\n");
      out.write("    $('input[name=bo_mail]').val('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeboardInfo.bo_mail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("');\r\n");
      out.write("    $('#bo_content').summernote('code', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeboardInfo.bo_content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("');\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    // 글쓰기\r\n");
      out.write("    $('#formBtn').on('click', function() {\r\n");
      out.write("    \t$(location).attr('href', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/freeboard/freeboardForm.do');\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    // 삭제\r\n");
      out.write("\t$('#deleteBtn').on('click', function() {\r\n");
      out.write("\t\t$(location).attr('href', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/freeboard/deleteFreeboard.do?bo_no=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeboardInfo.bo_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("');\r\n");
      out.write("\t});\r\n");
      out.write("    \r\n");
      out.write("    // 댓글\r\n");
      out.write("    $('#replyBtn').on('click', function() {\r\n");
      out.write("    \t\r\n");
      out.write("    \tif(eval('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty LOGIN_MEMBERINFO}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("')) {\r\n");
      out.write("\t    \t// /ddit/13/main.jsp?contentPage=/13/freeboard/freeboardReplyForm.jsp?rnum=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.rnum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("&bo_title=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeboardInfo.bo_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("\t    \t// 한글 처리\r\n");
      out.write("\t    \tconst bo_title = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeboardInfo.bo_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\t    \tconst queryString = '?rnum=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeboardInfo.rnum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("&bo_title=' + bo_title;\r\n");
      out.write("\t    \tconst parentInfo = '&bo_group=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeboardInfo.bo_group}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("&bo_seq=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeboardInfo.bo_seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("&bo_depth=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeboardInfo.bo_depth}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\t    \t$(location).attr('href', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/freeboard/freeboardReplyForm.do' + queryString + parentInfo);\r\n");
      out.write("    \t} else {\r\n");
      out.write("    \t\tBootstrapDialog.show({\r\n");
      out.write("    \t\t    title: '알림',\r\n");
      out.write("    \t\t    message: '로그인 후 작성이 가능합니다.'\r\n");
      out.write("    \t\t});\r\n");
      out.write("    \t}\r\n");
      out.write("    });\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("    \r\n");
      out.write("    // 목록\r\n");
      out.write("    $('#listBtn').on('click', function() {\r\n");
      out.write("    \t$(location).attr('href', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/freeboard/freeboardList.do');\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form class=\"form-horizontal\" role=\"form\" action=\"\" method=\"post\">\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t\t<label class=\"control-label col-sm-2\" for=\"bo_title\">제목:</label>\r\n");
      out.write("\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" id=\"bo_title\" name=\"bo_title\" >\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t\t<label class=\"control-label col-sm-2\" for=\"bo_nickname\">작성자 대화명:</label>\r\n");
      out.write("\t\t<div class=\"col-sm-10\"> \r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" id=\"bo_nickname\" name=\"bo_nickname\" >\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t\t<label class=\"control-label col-sm-2\" for=\"bo_pwd\">패스워드:</label>\r\n");
      out.write("\t\t<div class=\"col-sm-10\"> \r\n");
      out.write("\t\t\t<input type=\"password\" class=\"form-control\" id=\"bo_pwd\" name=\"bo_pwd\" >\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t\t<label class=\"control-label col-sm-2\" for=\"bo_mail\">메일:</label>\r\n");
      out.write("\t\t<div class=\"col-sm-10\"> \r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" id=\"bo_mail\" name=\"bo_mail\" >\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t\t<label class=\"control-label col-sm-2\" for=\"bo_content\">내용:</label>\r\n");
      out.write("\t\t<div class=\"col-sm-10\"> \r\n");
      out.write("\t\t\t<div id=\"bo_content\"><p></p></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t\t<label class=\"control-label col-sm-2\" for=\"bo_content\">첨부파일:</label>\r\n");
      out.write("\t\t<div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("\t\t\t<!-- Indicators -->\r\n");
      out.write("\t\t\t<ol class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("\t\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("\t\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("\t\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"3\"></li>\r\n");
      out.write("\t\t\t</ol>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<!-- Wrapper for slides -->\r\n");
      out.write("\t\t\t<div class=\"carousel-inner\" role=\"listbox\" style=\"height: 200px;\">\r\n");
      out.write("\t\t\t\t<div class=\"item active\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/thumbs/arch-1.jpg\" alt=\"pic1\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/thumbs/arch-2.jpg\" alt=\"pic2\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/thumbs/autumn-1.jpg\" alt=\"pic3\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/thumbs/boats-1.jpg\" alt=\"pic4\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Left and right controls -->\r\n");
      out.write("\t\t\t<a class=\"carousel-control left\" href=\"#myCarousel\" data-slide=\"prev\">&lsaquo;</a>\r\n");
      out.write("\t\t\t<a class=\"carousel-control right\" href=\"#myCarousel\" data-slide=\"next\">&rsaquo;</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-group\"> \r\n");
      out.write("\t\t<div class=\"col-sm-offset-2 col-sm-10\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-success\" id=\"formBtn\">글쓰기</button>\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-danger\" id=\"deleteBtn\">삭제</button>\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"replyBtn\">댓글</button>\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-info\" id=\"listBtn\">목록</button>\r\n");
      out.write("\t\t\t<button type=\"submit\" class=\"btn btn-default\" style=\"float: right\">수정</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
