/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2020-07-17 10:24:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user.freeboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class freeboardForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>자유게시글 등록</title>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t// 섬머노트를 div를 활용한 textarea에 추가.\r\n");
      out.write("\t// http://summernote.org 활용\r\n");
      out.write("    $('#bo_content').summernote({\r\n");
      out.write("    \t\tlang: 'ko-KR',\r\n");
      out.write("\t\t\theight: 150,\r\n");
      out.write("\t\t\tcodemirror: {\r\n");
      out.write("\t\t\ttheme: 'monokai'\r\n");
      out.write("\t\t}\r\n");
      out.write("    });\r\n");
      out.write("    // 포커스 처리\r\n");
      out.write("    // $('#bo_content').summernote( {focus: true} );\r\n");
      out.write("    // 값 취득\r\n");
      out.write("    // $('#bo_content').summernote('code');\r\n");
      out.write("    // 값 추가\r\n");
      out.write("    // $('#bo_content').summernote('code', '<font color=\"red\">추가글</font>');\r\n");
      out.write("    // 에디터 제거\r\n");
      out.write("    // $('#bo_content').summernote('destroy');\r\n");
      out.write("    \r\n");
      out.write("/* \tBootstrapDialog.show({\r\n");
      out.write("\t    title: '알럿창',\r\n");
      out.write("\t    message: '알럿창으로 활용하세요!'\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tBootstrapDialog.show({\r\n");
      out.write("        message: '컨펌 다이얼로그로 활용하세요!',\r\n");
      out.write("        buttons: [{\r\n");
      out.write("            label: 'Button 1'\r\n");
      out.write("        }, {\r\n");
      out.write("            label: 'Button 2',\r\n");
      out.write("            cssClass: 'btn-primary',\r\n");
      out.write("            action: function(){\r\n");
      out.write("                alert('Hi Orange!');\r\n");
      out.write("            }\r\n");
      out.write("        }, {\r\n");
      out.write("            icon: 'glyphicon glyphicon-ban-circle',\r\n");
      out.write("            label: 'Button 3',\r\n");
      out.write("            cssClass: 'btn-warning'\r\n");
      out.write("        }, {\r\n");
      out.write("            label: 'Close',\r\n");
      out.write("            action: function(dialogItself){\r\n");
      out.write("                dialogItself.close();\r\n");
      out.write("            }\r\n");
      out.write("        }]\r\n");
      out.write("    }); */\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form class=\"form-horizontal\" id=\"freeboardForm\" role=\"form\" \r\n");
      out.write("\t\t\taction=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/freeboard/insertFreeboard.do\" method=\"post\">\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t\t<label class=\"control-label col-sm-2\" for=\"bo_title\">제목:</label>\r\n");
      out.write("\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" id=\"bo_title\" name=\"bo_title\" placeholder=\"제목 입력...\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t\t<label class=\"control-label col-sm-2\" for=\"bo_nickname\">작성자 대화명:</label>\r\n");
      out.write("\t\t<div class=\"col-sm-10\"> \r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" id=\"bo_nickname\" name=\"bo_nickname\" placeholder=\"대화명 입력...\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"bo_writer\" name=\"bo_writer\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${LOGIN_MEMBERINFO.mem_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t\t<label class=\"control-label col-sm-2\" for=\"bo_pwd\">패스워드:</label>\r\n");
      out.write("\t\t<div class=\"col-sm-10\"> \r\n");
      out.write("\t\t\t<input type=\"password\" class=\"form-control\" id=\"bo_pwd\" name=\"bo_pwd\" placeholder=\"패스워드 입력...\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t\t<label class=\"control-label col-sm-2\" for=\"bo_mail\">메일:</label>\r\n");
      out.write("\t\t<div class=\"col-sm-10\"> \r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" id=\"bo_mail\" name=\"bo_mail\" placeholder=\"메일주소 입력...\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t\t<label class=\"control-label col-sm-2\" for=\"bo_content\">내용:</label>\r\n");
      out.write("\t\t<div class=\"col-sm-10\"> \r\n");
      out.write("\t\t\t<div id=\"bo_content\"><p>내용을 입력해주세요...</p></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t\t<label class=\"control-label col-sm-2\" for=\"file01\">첨부파일1:</label>\r\n");
      out.write("\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t <input type=\"file\" class=\"filestyle\" id=\"file01\" name=\"file01\" data-buttonName=\"btn-primary\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t\t<label class=\"control-label col-sm-2\" for=\"file02\">첨부파일2:</label>\r\n");
      out.write("\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t <input type=\"file\" class=\"filestyle\" id=\"file02\" name=\"file02\" data-buttonName=\"btn-primary\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-group\"> \r\n");
      out.write("\t\t<div class=\"col-sm-offset-2 col-sm-10\">\r\n");
      out.write("\t\t\t<button type=\"submit\" class=\"btn btn-info\" style=\"float: right\">등록</button>\r\n");
      out.write("\t\t\t<button type=\"reset\" class=\"btn btn-danger\" style=\"float: right\">취소</button>\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-primary listBtn\" style=\"float: right\">목록</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\r\n");
      out.write("\t\t$('#freeboardForm').submit(function() {\r\n");
      out.write("\t\t\tconst bo_title = $('input[name=bo_title]').val();\r\n");
      out.write("\t\t\tif(bo_title == \"\") {\r\n");
      out.write("\t\t\t\tinfoMsg('제목을 입력하세요');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tconst bo_nickname = $('input[name=bo_nickname]').val();\r\n");
      out.write("\t\t\tif(bo_nickname == \"\") {\r\n");
      out.write("\t\t\t\tinfoMsg('작성자 대화명을 입력해주세요.');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tconst bo_pwd = $('input[name=bo_pwd]').val();\r\n");
      out.write("\t\t\tif(bo_pwd == \"\") {\r\n");
      out.write("\t\t\t\tinfoMsg('게시글 비밀번호를 입력해주세요.');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tconst bo_mail = $('input[name=bo_mail]').val();\r\n");
      out.write("\t\t\tif(bo_pwd == \"\") {\r\n");
      out.write("\t\t\t\tinfoMsg('이메일을 입력해주세요.');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}s\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('.listBtn').on('click', function() {\r\n");
      out.write("\t\t\t$(location).attr('href', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/freeboard/freeboardList.do');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction infoMsg(value) {\r\n");
      out.write("\t\tBootstrapDialog.show({\r\n");
      out.write("\t\t    title: '알림창',\r\n");
      out.write("\t\t    message: value\r\n");
      out.write("\t\t});\r\n");
      out.write("\t};\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
